name: Build Engine Executable

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  my-job:
    name: Run MATLAB Script to Build C++ Engine Application
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        
      - name: Set runtime paths
        uses: matlab-actions/run-command@v2
        with:
          command: fh=fopen(getenv('GITHUB_ENV'),'a'); fprintf(fh,'LD_LIBRARY_PATH=%s/bin/glnxa64:%s/sys/os/glnxa64\n', matlabroot, matlabroot); fclose(fh);
      - name: view directories for debug
        uses: matlab-actions/run-command@v2
        with:
          command: ls([matlabroot '/bin/glnxa64']); ls([matlabroot '/sys/os/glnxa64']);
      - name: Run script
        uses: matlab-actions/run-command@v2
        with:
          command: myBuildScript
      - name: Get MATLAB root and run binary
        shell: bash
        run: |
          # Confirm LD_LIBRARY_PATH for debugging
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"

          # Run the application
          ./main
